# Generated by Django 4.2 on 2023-10-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clothes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("brand", models.CharField(max_length=20)),
                ("purchased", models.BigIntegerField()),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
