# Generated by Django 4.2 on 2023-10-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webbanhang_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("phone_number", models.BigIntegerField()),
                ("email", models.CharField(max_length=60)),
                ("Address", models.CharField(max_length=100)),
            ],
        ),
    ]
